Tasks:
  - CMakeConfigTask:
      cmake_cfg_path: "build"
      cmake_build_type: "Release"
      cmake_extra_args:
        # Optional, If use Highway
        - "-DHWY_ENABLE_TESTS=OFF"
        - "-DHWY_ENABLE_EXAMPLES=OFF"
        # Optional
        - "-DMLLM_CPU_BACKEND_COMPILE_OPTIONS=-march=native"
        - "-DMLLM_KERNEL_USE_THREADS=ON"
        - "-DMLLM_KERNEL_THREADS_VENDOR_OPENMP=ON"
        - "-DMLLM_KERNEL_USE_THREADS_VENDOR_MLLM=OFF"

  - CMakeBuildTask:
      cmake_cfg_path: "build"
